service: aws-lambda-auth

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

package:
  individually: True
  exclude:
    - 'node_modules/**'
    - 'package*'
    - 'README.md'
    - 'LICENSE'
    - '.gitignore'
    - 'requirements.txt'
    - 'ci/*'
    - '.github/**'

functions:
  hello:
    handler: src/handler.lambda_handler

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3
    dockerizePip: non-linux
