service: aws-lambda-auth

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

package:
  individually: True

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements
